#!/bin/sh
set -e
set -x
MCU=esp32 cargo +esp build -r --target xtensa-esp32-espidf --no-default-features --features=esp-wroom-32
espflash save-image --chip esp32 --partition-table ./partitions.csv ./target/xtensa-esp32-espidf/release/esp32temp firmware-wroom32.bin
# EOF
