[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
#target = "xtensa-esp32-espidf"
target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg",
    "mio_unsupported_force_poll_poll",
    "--cfg",
    "espidf_time64",
    "-C",
    "default-linker-libraries",
]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg",
    "mio_unsupported_force_poll_poll",
    "--cfg",
    "espidf_time64",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
CRATE_CC_NO_DEFAULTS = "1"
MCU = "esp32c3"
ESP_IDF_VERSION = "v5.3"
